### ISSUE TITLE
WkWebView support (and therefore, Chrome/Firefox/.. on iOS) is flaky/buggy :) 

### ISSUE THREAD

**Issue by ElielCohen** [aws/amazon-chime-sdk-component-library-react#475]
**Describe the bug**
Using the react demo, in a WkWebView on iOS, cause it to be buggy.
There is flickering, and most of the time, the camera is not correctly shared, or the user connected through this wkwebview is not visible on the other clients participating in the conversation. 

**To Reproduce**
Use the sample client of react chime sdk inside a wkwebview, therefore impacting as well Chrome, Firefox on iOS.

**Expected behavior**
Should work (since iOS 14.3) like when using the Safari web browser, or a SafariWebViewController (it's working well on wkWebView when using the pure javascript sample application).

**Smartphone (please complete the following information):**
 - Device: any iOS device
 - OS: 14.3+
 - Browser : WkWebView, Chrome, Firefox

**Additional context**
Using the pure javascript version, it works well, so I believe that the issue seems not inside the SDK that is shared between the two client applications, but in the react implementation.

**Comment by michhyun1** [comment]
Hi @ElielCohen, could you please verify a few things for use to properly see what the issue is:
1. What is the user-agent of the client that you are using?

**Comment by ElielCohen** [comment]
Hi,

So the issue is happening both on Firefox (using the Firefox default user agent) on Chrome (using the Chrome default user agent), or inside our application that employs a wkwebview to show the react sample app within. 

If I’m using the safari web view controller inside our application or if I use safari directly all works well.

Please note that the issue does not reproduce with the non react sample application.

Thanks,

Eliel Cohen
R&D Expert
Lead Mobile & Web Developer

**Comment by michhyun1** [comment]
@ElielCohen I deployed a version of the React demo and joined from both a desktop and iphone 11 on iOS Chrome. I did not observe any issues with joining the meeting or switching the video devices. Is there some steps that I am missing? Just to confirm, you deployed the react demo in our repo, right? Could you provide any relevant console logs? Thanks

**Comment by ElielCohen** [comment]
Hi Michael,

That’s surprising, I will try again to reproduce it today, and will update you accordingly.

Was the react demo was run locally or did u use the server less deployment ? 

Thanks,

Eliel Cohen
R&D Expert
Lead Mobile & Web Developer

**Comment by michhyun1** [comment]
I deployed the demo server less and joined the meeting

**Comment by ElielCohen** [comment]
Hi Michael,

So here is what you need to do to reproduce the issue,

Basically if you start the video on the desktop client, it will start failing on the chrome app on the iOS device.

Basically a flickering will start happening on the desktop client, and the attendee from the chrome browser will vanish from the attendee list, even if in the Chrome app on iOs he is still connected.

This behavior does not reproduce when using Safari on the iOS device, and reproduces constantly when using either Chrome, Firefox or any other WkWebView based implementation.

Please note that this issue does not happen on the non react based sample app.

Here are two videos showing the issue :

From the desktop , first bad behavior, then good behavior (without needing to leave the session) :

https://www.icloud.com/iclouddrive/0LUHQjCMN9txONei-Pgc1h8hQ#Desktop_side

From the mobile , bad behavior using Chrome, at first please note all is good, the issue starts when we start sharing video on the desktop side :

https://www.icloud.com/iclouddrive/0_u9W0ydWgWgan_8TBMAGj8qg#chrome_ios

Good behavior using Safari on the mobile :

https://www.icloud.com/iclouddrive/0KUadotbPX6ZCH7rlAQK84mcg#safari_ios

Thanks,

Eliel

**Comment by michhyun1** [comment]
Thanks @ElielCohen, could you please verify what versions of the react library and js sdk are you using? Thanks.

**Comment by michhyun1** [comment]
Hey @ElielCohen, could you try using the JS SDK version of 2.5.0+. It looks like you're on 2.4.1. Let me know if you see the same issues.

We added support for iOS Chrome and iOS FF on 2.5.0+ for the Chime SDK for JavaScript.
https://github.com/aws/amazon-chime-sdk-js/blob/master/CHANGELOG.md#added-2

**Comment by ElielCohen** [comment]
Gosh you’re right ;)

Just updated everything to latest and greatest, and now Chrome works flawesly.

I will check now other WkWebView implementation, but most likely all will be good. You can close it now, and if needed I’ll re-open it in case it still does not work as expected in custom wkWebView implementation.

Thanks a lot,

Eliel

**Comment by michhyun1** [comment]
Hey Eliel, thats great to hear. There is one other thing though - unfortunately we don't currently support a custom WKWebView implementation - if you're developing your own application and are using a WKWebview, you may run into the same issue that you had previously. We are tracking this task, but I can't give you an estimate of when we'll support this. Thanks! I'll close this issue, feel free to open this if needed.

**Comment by ElielCohen** [comment]
Does it mean that in my custom app, I should use the user-agent of chrome to have a good behavior ?

**Comment by michhyun1** [comment]
Yes, that is a workaround you can do. 

Here is the webkit based user-agents we support - https://github.com/aws/amazon-chime-sdk-js/blob/master/src/browserbehavior/DefaultBrowserBehavior.ts#L46

**Comment by ElielCohen** [comment]
Hi again Michael, 

When using such userAgent : "Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.163 Mobile/15E148 Safari/604.1", I am triggering normally the crios right ?

When using the user-agent above, I have still a strange behavior, in my wkwebview based application, all the streams received on the iOS device are black, the local video stream included. 

Strangely this does not impact my ability to send my local video, on the other side of the call, the stream sent from the iOS device is visible.

The improvement being therefore that the flickering stops on the web-browser side of the meeting.

Any idea how I could solve this issue ?

**Comment by michhyun1** [comment]
@ElielCohen I pushed a remote branch of the SDK called WKWebView - maybe you can try checking out that remote branch and trying your implementation on that. Let us know if you have any questions. 

As for the user-agent modification approach, could you verify what the browser name that the SDK is actually using when you make that change?

**Comment by ElielCohen** [comment]
Hi Michael, 

so yep I've used your branch for the SDK, but it does not bring any change yet from what GitHub shows me. Basically you simply added a iOS-webview user-agent inside the relevant wkwebview user agent array. 

I've doubled check the user-agent I'm using exactly this one : 

**Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.163 Mobile/15E148 Safari/604.1**

If I don't change it to this chrome user-agent for iOS, the web-view does not work well, by default, without any change to the userAgent of my wkWebView I'm exposing the following user-agent :

**Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148**

As you will guess, this does not match the user-agent you've added in the new branch, you have to change it to AppleWebKit I believe, as for now, if I'm not updating my user-agent to the chrome one above, I'm experiencing the same issue as before.

Beside that I've found a way to overcome the video (remote or local) being black, I've basically injected at url change a small javascript code, that will cycle in all existing video tag in the page and will play them.

This seems to solve it, although the approach is not the most elegant.

This does not solve though the audio issue, meaning that in wkwebview the audio from the microphone is not started, maybe a user-interaction issue here.

If you have any clue/idea how to overcome this, I'd be most thankful.

By the way since we make progress on this, maybe you should reopen this defect (I can't myself).

Thanks,

Eliel

**Comment by michhyun1** [comment]
We use the detect-browser module to detect the user-agent - it should detect your webview as 'ios-webview'. https://github.com/DamonOehlman/detect-browser/blob/master/src/index.ts#L93. Could you verify the user-agent you are getting - perhaps you can log the browser name that detect-browser detects. It should be printed at the very beginning of your logs: https://github.com/aws/amazon-chime-sdk-js/blob/85995a7fc9970bafe1963360381ebd93d481ce3b/src/meetingsession/DefaultMeetingSession.ts#L136

By the way, this isn't an officially supported feature of the SDK now, but it is on our roadmap to add WKWebView support fully.

**Comment by ElielCohen** [comment]
Hi Michael,

Right now the user-agent I'm exposing by default is the one I've shared above, meaning :
**Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148**

This does not seem to be taken in account by the change made in the WkWebView branch, since I have the problematic behavior that I get when not changing my user-agent to the crios one.

Thanks,

**Comment by michhyun1** [comment]
@ElielCohen we use detect-browser to get the browser name. In your case, it looks like your user agent matches this regex: https://github.com/DamonOehlman/detect-browser/blob/master/src/index.ts#L163

Perhaps you can help by pasting your console logs? Thanks

**Comment by ElielCohen** [comment]
Hi Michael,

Indeed I have checked the regex, and it should match the user agent, but never the less, this does not seem to work since I'm receiving these logs when reaching the chime app using the default wkwebview user agent :

[Warning] 2021-04-18T08:25:52.132Z [WARN] SDK - will retry due to status code TaskFailed and error: serial group task AudioVideoUpdate/7decdc45-1aa3-48b7-a137-688251fa81e3/29dbd48d-d6a0-b6ef-8a16-b6fc7ee19ce0 was canceled due to subtask AudioVideoUpdate/7decdc45-1aa3-48b7-a137-688251fa81e3/29dbd48d-d6a0-b6ef-8a16-b6fc7ee19ce0/Timeout15000ms error: serial group task AudioVideoUpdate/7decdc45-1aa3-48b7-a137-688251fa81e3/29dbd48d-d6a0-b6ef-8a16-b6fc7ee19ce0/Timeout15000ms/UpdateSession was canceled due to subtask AudioVideoUpdate/7decdc45-1aa3-48b7-a137-688251fa81e3/29dbd48d-d6a0-b6ef-8a16-b6fc7ee19ce0/Timeout15000ms/UpdateSession/SetRemoteDescriptionTask error: Failed to set remote answer sdp: Media section has more than one track specified with a=ssrc lines which is not supported with Unified Plan. (Prod, line 57)
[Warning] 2021-04-18T08:25:52.605Z [WARN] SDK - no stream found for tile=2 (Prod, line 57)

These errors are repeated on and on.

They do not appear if I'm using the chrome user agent.

I have retrieved these logs using the web inspector on safari for the wkwebview instance, is there other logs I should retrieve, if yes how and where ?

Thanks,

Eliel

**Comment by ElielCohen** [comment]
By the way through the inspector, I've run this and got the following user agent :

> navigator.userAgent
< "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko)"

This is ran on an iPad, that's why the user agent is now slightly different to before.
This does match the second regex for iOS-webview 

If I run the same command on an iPhone I get this :

> navigator.userAgent
< "Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"

Here the regex match as well but with the first one of iOS-webview.

Hope it helps understanding the issue.

Thanks,

Eliel

**Comment by ElielCohen** [comment]
Ok my bad , I did not deploy the new custom made sdk, but the regular one. That's why the default wkwebview agent did not work well. Now all is working good ;)

**Comment by michhyun1** [comment]
Awesome! For the record - that error message you got is typically an indication that Unified Plan is not enabled. By addiong the 'ios-webview' user agent to that array of supported browsers we're saying that we should enable Unified plan for that user-agent. Glad to see that it works! Closing this issue.

**Comment by ElielCohen** [comment]
When do you believe the branch WKWebView will be merged into master ?

**Comment by ElielCohen** [comment]
By the way, could you give a look at that other defect I've opened : 

https://github.com/aws/amazon-chime-sdk-js/issues/1197

It's really problematic as by default, the quality on some android devices is very low (video quality sent).

Thanks,

Eliel

**Comment by michhyun1** [comment]
@ElielCohen supporting WkWebView is on our roadmap, we'll try to get to it as soon as we can. Thanks! As for the other issue, I'll try to get some eyes on it.
